#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.scr43
    set site_3_0 $base.m44
    set site_3_0 $base.lab46
    set site_3_0 $base.lab47
    set site_3_0 $base.lab72
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m44" -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 1176x859+459+11
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3604 1041
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "ScriptBuilder"
    vTcl:DefineAlias "$top" "ScriptBuildTL" vTcl:Toplevel:WidgetProc "" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr43 \
        -background {#d9d9d9} -height 801 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 511 
    vTcl:DefineAlias "$top.scr43" "Scrolledtext1" vTcl:WidgetProc "ScriptBuildTL" 1

    $top.scr43.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    menu $top.m44 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $top.m44 add cascade \
        -menu "$top.m44.men45" -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label File 
    set site_3_0 $top.m44
    menu $site_3_0.men45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men45 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#loadScript} -font TkMenuFont \
        -foreground {#000000} -label {Load Script} -state normal 
    $site_3_0.men45 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#saveScript} -font TkMenuFont \
        -foreground {#000000} -label {Save Script} -state normal 
    $site_3_0.men45 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#destroy_window} -font TkMenuFont \
        -foreground {#000000} -label Exit -state normal 
    labelframe $top.lab46 \
        -foreground black -text {Add Measurement} -background {#d9d9d9} \
        -height 345 -width 590 
    vTcl:DefineAlias "$top.lab46" "AddMeasFrame" vTcl:WidgetProc "ScriptBuildTL" 1
    set site_3_0 $top.lab46
    entry $site_3_0.ent48 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black \
        -textvariable MeasNameVar 
    vTcl:DefineAlias "$site_3_0.ent48" "MeasNameEntry" vTcl:WidgetProc "ScriptBuildTL" 1
    ttk::combobox $site_3_0.tCo58 \
        -postcommand updateFuncBox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo58" "ProcBox" vTcl:WidgetProc "ScriptBuildTL" 1
    entry $site_3_0.ent60 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black \
        -textvariable StructNameVar 
    vTcl:DefineAlias "$site_3_0.ent60" "StructEntry" vTcl:WidgetProc "ScriptBuildTL" 1
    label $site_3_0.lab61 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Measurement Name} 
    vTcl:DefineAlias "$site_3_0.lab61" "MeasNameLabel" vTcl:WidgetProc "ScriptBuildTL" 1
    label $site_3_0.lab62 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text StructureName 
    vTcl:DefineAlias "$site_3_0.lab62" "StructLabel" vTcl:WidgetProc "ScriptBuildTL" 1
    label $site_3_0.lab63 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Procedure File} 
    vTcl:DefineAlias "$site_3_0.lab63" "ProcLabel" vTcl:WidgetProc "ScriptBuildTL" 1
    label $site_3_0.lab64 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Function to be performed} 
    vTcl:DefineAlias "$site_3_0.lab64" "FuncLabel" vTcl:WidgetProc "ScriptBuildTL" 1
    ttk::combobox $site_3_0.tCo65 \
        -postcommand updateArgs -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo65" "FuncBox" vTcl:WidgetProc "ScriptBuildTL" 1
    label $site_3_0.lab66 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text Arguments 
    vTcl:DefineAlias "$site_3_0.lab66" "ArgLabel" vTcl:WidgetProc "ScriptBuildTL" 1
    entry $site_3_0.ent67 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black \
        -textvariable ArgEntryVar 
    vTcl:DefineAlias "$site_3_0.ent67" "ArgEntry" vTcl:WidgetProc "ScriptBuildTL" 1
    entry $site_3_0.ent69 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black -state disabled \
        -textvariable ArgShowEntryVar 
    vTcl:DefineAlias "$site_3_0.ent69" "ArgShowEntry" vTcl:WidgetProc "ScriptBuildTL" 1
    button $site_3_0.but71 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command addMeasurement \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text AddMeasurement 
    vTcl:DefineAlias "$site_3_0.but71" "AddMeasButton" vTcl:WidgetProc "ScriptBuildTL" 1
    place $site_3_0.ent48 \
        -in $site_3_0 -x 10 -y 50 -width 424 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo58 \
        -in $site_3_0 -x 10 -y 150 -width 423 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent60 \
        -in $site_3_0 -x 10 -y 91 -width 424 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 10 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 10 -y 70 -anchor nw -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 10 -y 130 -width 81 -height 20 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 10 -y 179 -width 142 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo65 \
        -in $site_3_0 -x 10 -y 199 -width 423 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 10 -y 220 -anchor nw -bordermode ignore 
    place $site_3_0.ent67 \
        -in $site_3_0 -x 10 -y 270 -width 424 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent69 \
        -in $site_3_0 -x 10 -y 240 -width 424 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but71 \
        -in $site_3_0 -x 10 -y 300 -width 147 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab47 \
        -foreground black -text {Add Block} -background {#d9d9d9} -height 265 \
        -width 590 
    vTcl:DefineAlias "$top.lab47" "AddBlockFrame" vTcl:WidgetProc "ScriptBuildTL" 1
    set site_3_0 $top.lab47
    button $site_3_0.but80 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command addBlock -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text AddBlock 
    vTcl:DefineAlias "$site_3_0.but80" "AddBlockButton" vTcl:WidgetProc "ScriptBuildTL" 1
    label $site_3_0.lab81 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text BlockType 
    vTcl:DefineAlias "$site_3_0.lab81" "BlockTypeLabel" vTcl:WidgetProc "ScriptBuildTL" 1
    ttk::combobox $site_3_0.tCo82 \
        -textvariable BlockTypeBoxVar -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo82" "BlockTypeBox" vTcl:WidgetProc "ScriptBuildTL" 1
    label $site_3_0.lab83 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text BlockName 
    vTcl:DefineAlias "$site_3_0.lab83" "BlockNameLabel" vTcl:WidgetProc "ScriptBuildTL" 1
    entry $site_3_0.ent84 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black \
        -textvariable BlockNameVar 
    vTcl:DefineAlias "$site_3_0.ent84" "BlockNameEntry" vTcl:WidgetProc "ScriptBuildTL" 1
    checkbutton $site_3_0.che85 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left \
        -text {Use Local Binning Function} -variable useLocalBin 
    vTcl:DefineAlias "$site_3_0.che85" "LocalBinCheck" vTcl:WidgetProc "ScriptBuildTL" 1
    checkbutton $site_3_0.che86 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left \
        -text {Copy Measurements from previous Block} \
        -variable copyLastMeasBlock 
    vTcl:DefineAlias "$site_3_0.che86" "CopeCheck" vTcl:WidgetProc "ScriptBuildTL" 1
    label $site_3_0.lab87 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Local Binning Function} 
    vTcl:DefineAlias "$site_3_0.lab87" "LocalBinFuncLabel" vTcl:WidgetProc "ScriptBuildTL" 1
    label $site_3_0.lab88 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text File 
    vTcl:DefineAlias "$site_3_0.lab88" "LocalBinFuncFileLabel" vTcl:WidgetProc "ScriptBuildTL" 1
    ttk::combobox $site_3_0.tCo89 \
        -postcommand updateLocalBinFuncFuncBox \
        -textvariable LocalBinFuncFileBoxVar -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo89" "LocalBinFuncFileBox" vTcl:WidgetProc "ScriptBuildTL" 1
    label $site_3_0.lab90 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text Function 
    vTcl:DefineAlias "$site_3_0.lab90" "LocalBinFuncFuncLabel" vTcl:WidgetProc "ScriptBuildTL" 1
    ttk::combobox $site_3_0.tCo91 \
        -textvariable LocalBinFuncFuncBoxVar -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo91" "LocalBinFuncFuncBox" vTcl:WidgetProc "ScriptBuildTL" 1
    place $site_3_0.but80 \
        -in $site_3_0 -x 20 -y 220 -width 142 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 20 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.tCo82 \
        -in $site_3_0 -x 20 -y 50 -width 93 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 180 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.ent84 \
        -in $site_3_0 -x 180 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.che85 \
        -in $site_3_0 -x 190 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.che86 \
        -in $site_3_0 -x 190 -y 220 -anchor nw -bordermode ignore 
    place $site_3_0.lab87 \
        -in $site_3_0 -x 20 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.lab88 \
        -in $site_3_0 -x 20 -y 110 -anchor nw -bordermode ignore 
    place $site_3_0.tCo89 \
        -in $site_3_0 -x 20 -y 130 -width 413 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab90 \
        -in $site_3_0 -x 20 -y 160 -anchor nw -bordermode ignore 
    place $site_3_0.tCo91 \
        -in $site_3_0 -x 20 -y 180 -width 413 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab72 \
        -foreground black -text {Global Settings} -background {#d9d9d9} \
        -height 165 -width 590 
    vTcl:DefineAlias "$top.lab72" "GlobalSettingsFrame" vTcl:WidgetProc "ScriptBuildTL" 1
    set site_3_0 $top.lab72
    label $site_3_0.lab73 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Group By:} 
    vTcl:DefineAlias "$site_3_0.lab73" "GroupByLabel" vTcl:WidgetProc "ScriptBuildTL" 1
    ttk::combobox $site_3_0.tCo74 \
        -textvariable GroupByBoxVar -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo74" "GroupByBox" vTcl:WidgetProc "ScriptBuildTL" 1
    label $site_3_0.lab75 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text {Global Binning Function} 
    vTcl:DefineAlias "$site_3_0.lab75" "GlobBinFuncLabel" vTcl:WidgetProc "ScriptBuildTL" 1
    label $site_3_0.lab76 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text File 
    vTcl:DefineAlias "$site_3_0.lab76" "GlobBinFuncFileLabel" vTcl:WidgetProc "ScriptBuildTL" 1
    ttk::combobox $site_3_0.tCo77 \
        -postcommand updateGlobBinFuncFuncBox \
        -textvariable GlobBinFuncFileBoxVar -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo77" "GlobBinFuncFileBox" vTcl:WidgetProc "ScriptBuildTL" 1
    label $site_3_0.lab78 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text Function 
    vTcl:DefineAlias "$site_3_0.lab78" "GlobBinFuncFuncLabel" vTcl:WidgetProc "ScriptBuildTL" 1
    ttk::combobox $site_3_0.tCo79 \
        -textvariable GlobBinFuncFileBoxVar -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo79" "GlobBinFuncFuncBox" vTcl:WidgetProc "ScriptBuildTL" 1
    button $site_3_0.but97 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Update 
    vTcl:DefineAlias "$site_3_0.but97" "GlobalUpdateButton" vTcl:WidgetProc "ScriptBuildTL" 1
    place $site_3_0.lab73 \
        -in $site_3_0 -x 470 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.tCo74 \
        -in $site_3_0 -x 470 -y 60 -width 83 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.lab76 \
        -in $site_3_0 -x 10 -y 39 -width 24 -height 21 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo77 \
        -in $site_3_0 -x 10 -y 59 -width 423 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab78 \
        -in $site_3_0 -x 10 -y 80 -anchor nw -bordermode ignore 
    place $site_3_0.tCo79 \
        -in $site_3_0 -x 10 -y 100 -width 423 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but97 \
        -in $site_3_0 -x 10 -y 130 -width 137 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.scr43 \
        -in $top -x 650 -y 30 -width 511 -relwidth 0 -height 801 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 30 -y 20 -width 590 -relwidth 0 -height 345 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 30 -y 380 -width 590 -relwidth 0 -height 265 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab72 \
        -in $top -x 30 -y 660 -width 590 -relwidth 0 -height 165 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

