#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_4_0 .top37.tNo38.t0 
    set site_4_0 $site_4_0
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 482x188+694+307
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3604 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Search and Replace"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo38 \
        -width 454 -height 166 -takefocus {} 
    vTcl:DefineAlias "$top.tNo38" "RiderTab" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo38.t0 \
        -relief groove -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    vTcl:DefineAlias "$top.tNo38.t0" "RiderTab_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo38 add .top37.tNo38.t0 \
        -padding 0 -sticky nsew -state normal -text Replace -image {} \
        -compound none -underline -1 
    set site_4_0  $top.tNo38.t0
    label $site_4_0.lab40 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -text Replace 
    vTcl:DefineAlias "$site_4_0.lab40" "ReplaceLabel" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent41 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black \
        -textvariable SearchEntryVar 
    vTcl:DefineAlias "$site_4_0.ent41" "SearchEntry" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent42 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black \
        -textvariable ReplaceEntryVar 
    vTcl:DefineAlias "$site_4_0.ent42" "ReplaceEntry" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command replaceAll \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Replace All} 
    vTcl:DefineAlias "$site_4_0.but43" "ReplaceAllButton" vTcl:WidgetProc "Toplevel1" 1
    button $site_4_0.but44 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command exit -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Cancel 
    vTcl:DefineAlias "$site_4_0.but44" "Button2" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab40 \
        -in $site_4_0 -x 20 -y 60 -anchor nw -bordermode ignore 
    place $site_4_0.ent41 \
        -in $site_4_0 -x 100 -y 20 -width 324 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent42 \
        -in $site_4_0 -x 100 -y 60 -width 324 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.but43 \
        -in $site_4_0 -x 100 -y 100 -anchor nw -bordermode ignore 
    place $site_4_0.but44 \
        -in $site_4_0 -x 190 -y 100 -width 67 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo38 \
        -in $top -x 10 -y 10 -width 454 -relwidth 0 -height 166 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

